### ISSUE TITLE
What is the point and goal of ypywidgets

### ISSUE THREAD

**Issue by paddymul** [davidbrochart/ypywidgets#15]
David,

I saw that you are planning to move ypywidgets to the Jupyter Widgets group.

Can you give some explanation as to what the goals of ypywidgets are:

What pain point is it trying to solve?

How does it fix this problem?

What are the differences between ypywidgets and the existing approach?

Can you correct this sentence?
`YPYwidgets is a replacement for the existing ipywidgets package.  It is now based on pure JS objects as opposed to backbone.`

**Comment by davidbrochart** [comment]
Thanks for opening an issue @paddymul, I opened #16. Feel free to comment on it.
